groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting: if the node ins down for >= 1 minute
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance is down'
      description: 'Instance has been down for more than 1 minute !!!'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'