{
 "title": "flask web app dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Scrape duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"webapp\"}",
     "legendFormat": "scrape duration seconds"
    }
   ]
  },
  {
   "title": "WebApp CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=~\"webapp:8887\"}",
     "legendFormat": "cpu usage (s)"
    }
   ]
  },
  {
   "title": "Total Http requests (all flask endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=~\"webapp:8887\"}",
     "legendFormat": "total http requests"
    }
   ]
  }
 ]
}